import Head from "next/head";
import { v4 as uuidv4 } from "uuid";

import Header from "../components/Header";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";

export default function Home({ exploreData, cardsData }) {
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, location, distance }) => (
              <li key={uuidv4()}>
                <SmallCard img={img} location={location} distance={distance} />
              </li>
            ))}
          </ul>
        </section>

        <section className="pt-6">
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <ul className="flex space-x-3 overflow-scroll scrollbar-hide pb-3">
            {cardsData?.map(({ img, title }) => (
              <li key={uuidv4()}>
                <MediumCard img={img} title={title} />
              </li>
            ))}
          </ul>
        </section>

        <LargeCard
          img="https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>

      <Footer></Footer>
    </>
  );
}

export const getStaticProps = async () => {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then((res) => res.json());
  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then((res) => res.json());

  return {
    props: { exploreData, cardsData },
  };
};
