import { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";
import moment from "moment";

import Header from "../components/Header";
import Banner from "../components/Banner";
import Explore from "../components/Explore";
import LiveAnywhere from "../components/LiveAnywhere";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

export default function Home() {
  const [localListings, setLocalListings] = useState(null);

  function propertyTypes() {
    const categories = [...new Set(localListings?.map((property) => property.type))];
    console.log("categories", categories);

    const categorizedListings = categories.map((category) => {
      return localListings?.filter((property) => property.type === category);
    });
    console.log(categorizedListings);
    return categorizedListings;
  }

  useEffect(() => {
    navigator.geolocation.getCurrentPosition(function (position) {
      console.log("Latitude is :", position.coords.latitude);
      console.log("Longitude is :", position.coords.longitude);

      window.localStorage.getItem("listings");
      const cachedLocalListings = JSON.parse(window.localStorage.getItem("listings"));
      console.log("read from cache:", cachedLocalListings);
      console.log(cachedLocalListings);
      if (cachedLocalListings) {
        setLocalListings(
          cachedLocalListings?.filter((property) => property.id.toString().length === 8)
        );
      } else {
        const options = {
          method: "GET",
          url: "https://airbnb13.p.rapidapi.com/search-geo",
          params: {
            ne_lat: position.coords.latitude + 1,
            ne_lng: position.coords.longitude + 1,
            sw_lat: position.coords.latitude - 1,
            sw_lng: position.coords.longitude - 1,
            checkin: moment().add(1, "days").format("YYYY-MM-DD"),
            checkout: moment().add(2, "days").format("YYYY-MM-DD"),
            adults: "1",
            page: "1",
          },
          headers: {
            "X-RapidAPI-Key": process.env.airbnbApiKey,
            "X-RapidAPI-Host": process.env.airbnbApiHost,
          },
        };

        axios
          .request(options)
          .then(function (response) {
            console.log(response.data.results);
            window.localStorage.setItem("listings", JSON.stringify(response.data.results));
            setLocalListings(
              response.data.results?.filter((property) => property.id.toString().length === 8)
            );
          })
          .catch(function (error) {
            console.error(error);
          });
      }
    });
  }, []);

  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner localListings={localListings} />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <Explore localListings={localListings} />
        <LiveAnywhere propertyTypes={propertyTypes()} />
        <LargeCard />
      </main>
      <Footer />
    </>
  );
}
